scrumapp_core/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from scrumapp.views import AddStoriesToSprintView, PostList, PostCreate, ProjectDetail, ProjectList, ProjectUpdate, SprintCreate, SprintDetail, SprintUpdate, SprintDelete, StoryCreate, StoryDetail, StoryStatusUpdate, StoryUpdate, StoryDelete, TaskClaim, TaskCreate, TaskUpdate, TaskDelete, TaskTimeStop, TaskTimeStart, TaskUnclaim, TaskFinish, LoggedTimeList, CommentListView, CreateCommentView, ProfileUpdateView, ChangePasswordView,PostDeleteView, CommentDeleteView, StoryNoteCreate

urlpatterns = [
    path('projects', ProjectList.as_view(), name='project_list'),
    path('projects/<int:project_id>', ProjectDetail.as_view(), name='project_detail'),
    path('projects/<int:project_id>/edit', ProjectUpdate.as_view(), name='project_edit'),
    path('projects/<int:project_id>/add_stories_to_sprint', AddStoriesToSprintView.as_view(), name='add_stories_to_sprint'),

    path('projects/<int:project_id>/sprints/<int:pk>', SprintDetail.as_view(), name='sprint_detail'),
    path('projects/<int:project_id>/sprints/create', SprintCreate.as_view(), name='sprint_create'),
    path('projects/<int:project_id>/sprints/<int:pk>/edit', SprintUpdate.as_view(), name='sprint_edit'),
    path('projects/<int:project_id>/sprints/<int:pk>/delete', SprintDelete.as_view(), name='sprint_delete'),

    path('projects/<int:project_id>/stories/<int:pk>', StoryDetail.as_view(), name='story_detail'),
    path('projects/<int:project_id>/stories/create', StoryCreate.as_view(), name='story_create'),
    path('projects/<int:project_id>/stories/<int:pk>/edit', StoryUpdate.as_view(), name='story_edit'),
    path('projects/<int:project_id>/stories/<int:pk>/status', StoryStatusUpdate.as_view(), name='story_status'),
    path('projects/<int:project_id>/stories/<int:pk>/delete', StoryDelete.as_view(), name='story_delete'),
    path('projects/<int:project_id>/stories/<int:story_id>/create_note', StoryNoteCreate.as_view(), name='story_note'),
    

    path('projects/<int:project_id>/stories/<int:story_id>/tasks/create', TaskCreate.as_view(), name='task_create'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/edit', TaskUpdate.as_view(), name='task_edit'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/delete', TaskDelete.as_view(), name='task_delete'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/claim', TaskClaim.as_view(), name='task_claim'),

    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/start_tracking', TaskTimeStart.as_view(), name='task_start'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/stop_tracking', TaskTimeStop.as_view(), name='task_stop'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/unclaim', TaskUnclaim.as_view(), name='task_unclaim'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/finish', TaskFinish.as_view(), name='task_finish'),
    path('projects/<int:project_id>/stories/<int:pk>/list_time', LoggedTimeList.as_view(), name='tracked_time'),
    

    path('projects/<int:project_id>/posts/create', PostCreate.as_view(), name='post_create'),
    path('projects/<int:project_id>/posts', PostList.as_view(), name='post_list'),

    path('projects/<int:project_id>/posts/<int:post_id>/comments/', CommentListView.as_view(), name='comment_list'),
    path('projects/<int:project_id>/posts/<int:post_id>/comments/create/', CreateCommentView.as_view(), name='create_comment'),
    path('projects/<int:project_id>/post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('projects/<int:project_id>/comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),

    path('update-profile/', ProfileUpdateView.as_view(), name='update_profile'),
    path('password-change/', ChangePasswordView.as_view(), name='passwordchange'),

    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('', lambda r: redirect('project_list'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Duplicate URL names are allowed by Django, but we don't want them in this project, so make sure they don't happen
names = [pattern.name for pattern in urlpatterns if getattr(pattern, "name", None)]
assert len(names) == len(set(names)), f"Duplicate URL names: {names}"

scrumapp/models.py
from functools import cached_property

from django.contrib.auth.models import User
from django.db import models
from django.forms import ValidationError
from django.urls import reverse_lazy
from django.utils import timezone

from scrumapp.validators import date_not_in_past


class RoleEnum(models.TextChoices):
    DEVELOPER = "DEV", "Developer"
    SCRUM_MASTER = "SM", "Scrum Master"
    PRODUCT_OWNER = "PO", "Product Owner"

class ProjectMember(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    project = models.ForeignKey("Project", on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=RoleEnum.choices)

class Project(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)

    sprints: 'SprintQuerySet'
    stories: 'StoryQuerySet'

    def __str__(self):
        return self.name
    
    # These use .all() to take advantage of query caching, but we still need to confirm queries are actually cached
    
    @cached_property
    def product_owner(self) -> User:
        for pm in self.projectmember_set.all():
            if pm.role == RoleEnum.PRODUCT_OWNER:
                return pm.user
            
    @cached_property
    def scrum_master(self) -> User:
        for pm in self.projectmember_set.all():
            if pm.role == RoleEnum.SCRUM_MASTER:
                return pm.user
    
    @cached_property
    def developers(self) -> list[User]:
        return [pm.user for pm in self.projectmember_set.all() if pm.role == RoleEnum.DEVELOPER]

    def get_absolute_url(self):
        return reverse_lazy("project_detail", kwargs={"project_id": self.id})
    

# A custom manager for Sprint so we can DRY our queries
class SprintQuerySet(models.QuerySet):
    def active(self):
        now = timezone.now()
        return self.filter(start_date__lte=now, end_date__gte=now)

    def future(self):
        return self.filter(start_date__gt=timezone.now())
    
    def past(self):
        return self.filter(end_date__lt=timezone.now())


class Sprint(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="sprints")
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    velocity = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="Velocity (pts)")

    objects = SprintQuerySet.as_manager()

    def __str__(self):
        return self.name

    def clean(self):
        if self.start_date > self.end_date:
            raise ValidationError({
                "start_date": "Start date cannot be after end date"
            })
        # Only run this validation on new objects (when creating)
        if self.id is None:
            if self.start_date < timezone.now().date():
                raise ValidationError({
                    "start_date": "Start date cannot be in the past"
                })

        # TODO: turn this into a field validation
        if self.velocity == 0:
            raise ValidationError({
                "velocity": "Velocity cannot be 0"
            })

    def get_absolute_url(self):
        return reverse_lazy("sprint_detail", kwargs={"project_id": self.project.id, "pk": self.id})

    def is_future(self):
        return self.start_date > timezone.now().date()

    def is_active(self):
        return self.start_date <= timezone.now().date() and \
            self.end_date >= timezone.now().date()


class StoryQuerySet(models.QuerySet):
    def product_backlog(self):
        return (self.filter(sprint=None)
            .exclude(status=Story.Status.ACCEPTED) |
            self.filter(status=Story.Status.REJECTED)) \
            .exclude(priority=Story.Priority.WONT_HAVE)


class Story(models.Model):
    class Priority(models.IntegerChoices):
        MUST_HAVE = 1, 'Must have'
        SHOULD_HAVE = 2, 'Should have'
        COULD_HAVE = 3, 'Could have'
        WONT_HAVE = 4, "Won't have at this time"

    class Status(models.IntegerChoices):
        UNKNOWN = 0, 'Unknown'
        ACCEPTED = 1, 'Accepted'
        REJECTED = 2, 'Rejected'

    objects = StoryQuerySet.as_manager()

    sprint = models.ForeignKey(Sprint, null=True, blank=True, on_delete=models.SET_NULL)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="stories")
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    acceptance_tests = models.TextField(blank=True)
    priority = models.IntegerField(choices=Priority)
    status = models.IntegerField(choices=Status, default=Status.UNKNOWN)
    business_value = models.FloatField(verbose_name="Business value")
    time_estimate = models.FloatField(verbose_name="Time estimate (pts)", null=True, blank=True)
    finished = models.BooleanField(default=False)
    soft_deleted = models.BooleanField(default=False)

    tasks: 'models.QuerySet[Task]'
    notes: 'models.QuerySet[StoryNotes]'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("story_detail", kwargs={"project_id": self.project.id, "pk": self.id})

    def is_accepted(self):
        return self.status == Story.Status.ACCEPTED

    def is_recjected(self):
        return self.status == Story.Status.REJECTED

    def clean(self):
        if self.business_value is not None:
            if self.business_value <= 0 or self.business_value > 10:
                raise ValidationError({
                    "business_value": "Business value should be between 1 and 10"
                })

    @cached_property
    def is_finished(self):
        finished_tasks_count = self.tasks.filter(status=Task.Status.FINISHED).count()
        return finished_tasks_count == self.tasks.count() and finished_tasks_count > 0
    
    class Meta:
        verbose_name_plural = "stories"

class StoryNotes(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE, related_name="notes")
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    content = models.TextField()
    time_posted = models.DateTimeField(auto_now_add=True)

class Task(models.Model):
    class Status(models.IntegerChoices):
        UNCLAIMED = 0, 'Unclaimed'
        CLAIMED = 1, 'Claimed'
        ACTIVE = 2, 'Active'
        FINISHED = 3, 'Finished'

    story = models.ForeignKey(Story, on_delete=models.CASCADE, related_name="tasks")
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    status = models.IntegerField(choices=Status, default=Status.UNCLAIMED)
    assigned_to = models.ForeignKey("auth.User", on_delete=models.SET_NULL, null=True, blank=True)
    hours = models.IntegerField()
    date = models.DateField(default=timezone.now)
    soft_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class TrackedTime(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="work_logs")
    date = models.DateField(default=timezone.now)
    # Time when the task was started (if not running, this is None)
    started = models.DateTimeField(null=True, blank=True)
    hours = models.FloatField(null=True, blank=True)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)

    class Meta:
        unique_together = ('task', 'date', 'user')


class Post(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    time_posted = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("post_list", kwargs={"project_id": self.project.id})
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    content = models.TextField()
    time_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user.username} on {self.post.title}"

scrumapp/templates/scrumapp/change_passowrd.html
{% extends "scrumapp/base.html" %}

{% block main %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center mt-4 mb-4">Change Your Password</h2>
            {% if form.errors %}
                <div class="alert alert-danger">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <p>{{ field.label }}: {{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_old_password">Old Password</label>
                    <input type="password" name="old_password" id="id_old_password" class="form-control" placeholder="Old Password" required>
                </div><br>
                <div class="form-group">
                    <label for="id_new_password1">New Password</label>
                    <input type="password" name="new_password1" id="id_new_password1" class="form-control" placeholder="New Password" required>
                </div><br>
                <div class="form-group">
                    <label for="id_new_password2">Confirm New Password</label>
                    <input type="password" name="new_password2" id="id_new_password2" class="form-control" placeholder="Confirm New Password" required>
                </div>
                <br><button type="submit" class="btn btn-primary btn-block">Update Password</button>
            </form>
        </div>
    </div>
</div>
{% endblock main %}

scrumapp/templates/scrumapp/comment_confirm_delete.html
{% extends "scrumapp/base.html" %}
{% load scrumapp %} 

{% block main %}
  <form method="post">{% csrf_token %}
      <p>Are you sure you want to delete this comment?</p>
      <input type="submit" value="Confirm">
  </form>
{% endblock %}

scrumapp/templates/scrumapp/post_confirm_delete.html
{% extends "scrumapp/base.html" %}
{% load scrumapp %} 

{% block main %}
  <form method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ object.title }}"?</p>
      <input type="submit" value="Confirm">
  </form>
{% endblock %}

scrumapp/templates/scrumapp/post_form.html
{% extends "scrumapp/base.html" %}
{% load crispy_forms_filters %}
{% block main %}

<div class="container">
    <div class="row">
        <!-- TODO navigate back to post -->
        <a href="{{project.get_absolute_url}}" class="btn btn-outline-dark btn-sm py-1 my-2 col-1">
            <i class="fa-solid fa-arrow-left"></i>
        </a>
        <h2 class="col text-center">{{form.is_bound|yesno:"Edit,Create"}} post</h2>
    </div>
    <div class="row">
        <div class="col">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="{{project.get_absolute_url}}" class="btn btn-danger">Cancel</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

scrumapp/templates/scrumapp/post_list.html
{% extends "scrumapp/base.html" %}
{% load scrumapp %} 
{% block title %}Project wall{% endblock title %}

{% block main %}
<section>
    <header class="row mb-3">
        <a href="{{ project.get_absolute_url }}" class="col-1 btn btn-outline-dark btn-sm py-1 my-2">
            <i class="fa-solid fa-arrow-left"></i>
        </a>
        <h2 class="col font-weight-bold text-center">Project wall</h2>
        <a href="{% url 'post_create' project_id=project.id %}" class="col-1 btn btn-success btn-sm my-2">
            <i class="fa-solid fa-plus"></i> New post
        </a>
    </header>
    <main>
    {% for post in posts %}
    <article class="card mb-2">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">
                <i class="fa-solid fa-user"></i> {{ post.user }}
                <i class="fa-solid fa-clock"></i> {{ post.time_posted|date:"M d, Y H:i" }}
            </h6>
            <p class="card-text">{{ post.description|newline_br }}</p>

            <div class="comments-section mb-2">
                {% for comment in post.comments.all %}
                <div class="comment mb-1">
                    <strong>{{ comment.user.username }}</strong> ({{ comment.time_posted|date:"M d, Y H:i" }}): {{ comment.content }}
                    {% if user_role == 'SM' %}
                    <a href="{% url 'comment_delete' project_id=post.project.id pk=comment.id %}" class="btn btn-danger btn-sm">Delete</a>  <!-- Link to delete comment -->
                    {% endif %}
                </div>
                {% empty %}
                <p class="text-muted">No comments yet.</p>
                {% endfor %}
            </div>

            <form action="{% url 'create_comment' project_id=post.project.id post_id=post.id %}" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <textarea name="content" class="form-control" placeholder="Write a comment..." rows="1"></textarea>
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit">Post</button>
                    </div>
                </div>
            </form>
            {% if user_role == 'SM' %}
            <a href="{% url 'post_delete' project_id=post.project.id pk=post.id %}" class="btn btn-danger btn-sm mt-2">Delete Post</a>  <!-- Link to delete post -->
            {% endif %}
        </div>
    </article>
    {% empty %}
    <span class="text-muted">The wall is empty</span>
    {% endfor %}
    </main>
</section>
{% endblock main %}

scrumapp/templates/scrumapp/project_detail.html
{% extends "scrumapp/base.html" %}
{% load crispy_forms_filters %}
{% load scrumapp %}

{% block title %}Project: {{ project.name }}{% endblock %}

{% block main %}

<section>
    <div class="row">
        <a href="{% url 'project_list' %}" class="col-1 btn btn-outline-dark btn-sm py-1 my-2">
            <i class="fa-solid fa-arrow-left"></i>
        </a>
        <h2 class="col text-center">Project: {{ project.name }}</h2>
    </div>
    <div class="row">
        <div class="col">
            {{ project.description|newline_br }}
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col">
            <strong><i class="fa-solid fa-user-ninja"></i> Scrum master:</strong> {{ project.scrum_master }}
            <br/>
            <strong><i class="fa-solid fa-user-tie"></i> Product owner:</strong> {{project.product_owner }}
            <br/>
            <strong><i class="fa-solid fa-users"></i> Developers:</strong> {% for member in project.developers %}{{member}}{% if not forloop.last %}, {% endif %}{% endfor %}
        </div>
        <div class="col-5">
            <canvas id="burndownChart" width="400" height="200"></canvas>
        </div>
    </div>
    <div class="row mt-2">
        <a href="{% url 'post_list' project_id=project.id %}" class="btn btn-primary btn-sm col-2 mx-1">
            <i class="fa-solid fa-comment"></i>
            Project wall
        </a>
        <a href="{% url 'project_edit' project_id=project.id %}" class="btn btn-warning btn-sm col-2 mx-1">
            <i class="fa-solid fa-edit"></i>
            Edit
        </a>
        {% if request.user.is_superuser %}
        <a target="_blank" href="/admin/scrumapp/project/{{project.id}}/change/" class="btn btn-danger btn-sm col-2 mx-1">
            <i class="fa-solid fa-cog"></i>
            Admin
        </a>
        {% endif %}
    </div>
</section>

<section class="row p-3 my-2">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
            var ctx = document.getElementById('burndownChart').getContext('2d');
            var ideal_burn_down = JSON.parse("{{ ideal_burn_down }}");
            var actual_burn_down = JSON.parse("{{ actual_burn_down }}");
            var labels = ideal_burn_down.map((_, i) => i + 1);
            var burndownChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: labels,
                    datasets: [{
                        label: 'Ideal burndown',
                        // Load data from django project view ideal_burn_down
                        data: ideal_burn_down,
                        borderColor: 'rgba(0, 0, 0, 0.5)',
                        fill: false
                    }, {
                        label: 'Actual burndown',
                        data: actual_burn_down,
                        borderColor: 'rgba(0, 0, 255, 0.5)',
                        fill: false
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
        </script>
    </div>
</section>
<section class="row p-3 my-2">
    <a href="{% url 'sprint_create' project.id %}?next={{request.url}}" class="btn col-1 btn-success btn-sm my-2 mx-2 ms-auto">
        <i class="fa fa-plus"></i> Sprint
    </a>
    <a href="{% url 'story_create' project.id %}?next={{request.url}}" class="btn col-1 btn-primary btn-sm my-2 mx-2">
        <i class="fa fa-plus"></i> Story
    </a>
    <nav>
        <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
            <button class="nav-link active" id="nav-active-tab" data-bs-toggle="tab" data-bs-target="#nav-active"
                type="button" role="tab" aria-controls="nav-active" aria-selected="true">Active sprints</button>
            <button class="nav-link" id="nav-future-tab" data-bs-toggle="tab" data-bs-target="#nav-future" type="button"
                role="tab" aria-controls="nav-future" aria-selected="false">Future sprints</button>
            <button class="nav-link" id="nav-past-tab" data-bs-toggle="tab" data-bs-target="#nav-past" type="button"
                role="tab" aria-controls="nav-past" aria-selected="false">Past sprints</button>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-active" role="tabpanel" aria-labelledby="nav-active-tab">
            {% include "scrumapp/partial/sprint_list.html" with sprints=active %}
        </div>
        <div class="tab-pane fade" id="nav-future" role="tabpanel" aria-labelledby="nav-future-tab">
            {% include "scrumapp/partial/sprint_list.html" with sprints=future %}
        </div>
        <div class="tab-pane fade" id="nav-past" role="tabpanel" aria-labelledby="nav-past-tab">
            {% include "scrumapp/partial/sprint_list.html" with sprints=past %}
        </div>
    </div>

</section>


<section class="row p-3 my-2">
    <h3>Product backlog</h3>
    <nav>
        <div class="nav nav-tabs nav-fill" id="nav-tabs2" role="tablist">
            <button class="nav-link active" id="tabs2-1-nav" data-bs-toggle="tab" data-bs-target="#tabs2-1" type="button" role="tab" aria-controls="tabs2-1" aria-selected="true">Open</button>
            <button class="nav-link" id="tabs2-2-nav" data-bs-toggle="tab" data-bs-target="#tabs2-2" type="button" role="tab" aria-controls="tabs2-2" aria-selected="false">In sprint</button>
            <button class="nav-link" id="tabs2-3-nav" data-bs-toggle="tab" data-bs-target="#tabs2-3" type="button" role="tab" aria-controls="tabs2-3" aria-selected="false">Accepted</button>
            <button class="nav-link" id="tabs2-4-nav" data-bs-toggle="tab" data-bs-target="#tabs2-4" type="button" role="tab" aria-controls="tabs2-4" aria-selected="false">Future</button>
        </div>
    </nav>
    <div class="tab-content" id="tabs2">

        <!-- Open -->
        <div class="tab-pane fade show active" id="tabs2-1" role="tabpanel" aria-labelledby="tabs2-2-nav">
            {% if stories_has_estimate %}
                {% if active %}
                <form method="POST" action="{% url 'add_stories_to_sprint' project_id=project.id %}">
                    <div class="f-end">
                        {% csrf_token %}
                        {{ add_to_sprint_form.sprint }}
                        <button type="submit" class="btn btn-primary btn-sm">Add selected to active sprint</button>
                    </div>
                    {% include "scrumapp/partial/story_list.html" with stories=stories_has_estimate checkbox=True show_time_estimate=True %}
                </form>
                {% else %}
                {% include "scrumapp/partial/story_list.html" with stories=stories_has_estimate show_time_estimate=True %}
                {% endif %}
            {% endif %}

            {% if stories_needs_estimate %}
            <h4 class="mt-3">Time estimate needed</h4>
            {% include "scrumapp/partial/story_list.html" with stories=stories_needs_estimate checkbox=False %}
            {% endif %}

        </div>

        <!-- In sprint -->
        <div class="tab-pane fade" id="tabs2-2" role="tabpanel" aria-labelledby="tabs2-3-nav">
            {% include "scrumapp/partial/story_list.html" with stories=stories_in_sprint %}
        </div>

        <!-- Accepted -->
        <div class="tab-pane fade" id="tabs2-3" role="tabpanel" aria-labelledb&y="tabs2-4-nav">
            {% include "scrumapp/partial/story_list.html" with stories=stories_accepted %}
        </div>

        <!-- Future -->
        <div class="tab-pane fade" id="tabs2-4" role="tabpanel" aria-labelledby="tabs2-5-nav">
            {% include "scrumapp/partial/story_list.html" with stories=stories_future %}
        </div>

    </div>

</section>

{% endblock %}

scrumapp/templates/scrumapp/sprint_detail.html
{% extends "scrumapp/base.html" %}
{% load scrumapp %}

{% block title %}Sprint: {{ sprint.name }}{% endblock %}
{% block main %}

<section>    
    <div class="row">
        <a href="{{ project.get_absolute_url }}"  class="col-1 btn btn-outline-dark btn-sm py-1 my-2">
            <i class="fa-solid fa-arrow-left"></i>
        </a>
        <h2 class="col font-weight-bold text-center">Sprint: {{ sprint.name }}</h2>
    </div>
    <div class="col">
        <strong>Date: </strong> {{ sprint.start_date }} - {{ sprint.end_date }}
        {% if is_active %}
        <strong>(Active)</strong>
        {% endif %}
    </div>
    <div class="col">
        <strong>Velocity:</strong> {{ sprint.velocity|default_if_none:"?" }}
    </div>
    <p class="my-2 py-1 col">{{ sprint.description|newline_br }}</p>

    {% if not is_active %}
        <a href="{% url 'sprint_edit' project_id=sprint.project.id pk=sprint.id %}" class="btn btn-warning btn-sm col-1">
            <i class="fa-solid fa-edit"></i>
            Edit
        </a> 
    {% endif %}
    {% if sprint.is_future %}
    <a href="{% url 'sprint_delete' project_id=sprint.project.id pk=sprint.id %}" class="btn btn-danger btn-sm col-1">
        <i class="fa-solid fa-trash"></i>
        Delete
    </a> 
    {% endif %}
    {% if request.user.is_superuser %}
        <a target="_blank" href="/admin/scrumapp/sprint/{{sprint.id}}/change/" class="btn btn-danger btn-sm col-1">
            <i class="fa-solid fa-cog"></i>
            Admin
        </a>
    {% endif %}
    
    <h4 class="my-2 col text-center">{% if is_active %}Sprint backlog{% else %}Stories{% endif %}</h4>
    {% include 'scrumapp/partial/story_list.html' with stories=sprint.story_set.all remove=True show_tasks=True show_accept=True %}


</section>


{% endblock %}

scrumapp/templates/scrumapp/story_confirm_delete.html
{% extends "scrumapp/base.html" %}
{% load crispy_forms_filters %}

{% block main %}

<h2>Delete story {{ object }}</h2>


<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete story "{{ object }}"?</p>
    {{ form }}
    <button type="submit" class="btn btn-danger btn-sm col-1">
        Confirm
    </button>
</form>

{% endblock %}