scrumapp_core/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from scrumapp.views import AddStoriesToSprintView, PostList, PostCreate, ProjectDetail, ProjectList, ProjectUpdate, SprintCreate, SprintDetail, SprintUpdate, SprintDelete, StoryCreate, StoryDetail, StoryStatusUpdate, StoryUpdate, StoryDelete, TaskClaim, TaskCreate, TaskUpdate, TaskDelete, TaskTimeStop, TaskTimeStart, TaskUnclaim, TaskFinish, LoggedTimeList, CommentListView, CreateCommentView, ProfileUpdateView, ChangePasswordView,PostDeleteView, CommentDeleteView, StoryNoteCreate

urlpatterns = [
    path('projects', ProjectList.as_view(), name='project_list'),
    path('projects/<int:project_id>', ProjectDetail.as_view(), name='project_detail'),
    path('projects/<int:project_id>/edit', ProjectUpdate.as_view(), name='project_edit'),
    path('projects/<int:project_id>/add_stories_to_sprint', AddStoriesToSprintView.as_view(), name='add_stories_to_sprint'),

    path('projects/<int:project_id>/sprints/<int:pk>', SprintDetail.as_view(), name='sprint_detail'),
    path('projects/<int:project_id>/sprints/create', SprintCreate.as_view(), name='sprint_create'),
    path('projects/<int:project_id>/sprints/<int:pk>/edit', SprintUpdate.as_view(), name='sprint_edit'),
    path('projects/<int:project_id>/sprints/<int:pk>/delete', SprintDelete.as_view(), name='sprint_delete'),

    path('projects/<int:project_id>/stories/<int:pk>', StoryDetail.as_view(), name='story_detail'),
    path('projects/<int:project_id>/stories/create', StoryCreate.as_view(), name='story_create'),
    path('projects/<int:project_id>/stories/<int:pk>/edit', StoryUpdate.as_view(), name='story_edit'),
    path('projects/<int:project_id>/stories/<int:pk>/status', StoryStatusUpdate.as_view(), name='story_status'),
    path('projects/<int:project_id>/stories/<int:pk>/delete', StoryDelete.as_view(), name='story_delete'),
    path('projects/<int:project_id>/stories/<int:story_id>/create_note', StoryNoteCreate.as_view(), name='story_note'),
    

    path('projects/<int:project_id>/stories/<int:story_id>/tasks/create', TaskCreate.as_view(), name='task_create'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/edit', TaskUpdate.as_view(), name='task_edit'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/delete', TaskDelete.as_view(), name='task_delete'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/claim', TaskClaim.as_view(), name='task_claim'),

    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/start_tracking', TaskTimeStart.as_view(), name='task_start'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/stop_tracking', TaskTimeStop.as_view(), name='task_stop'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/unclaim', TaskUnclaim.as_view(), name='task_unclaim'),
    path('projects/<int:project_id>/stories/<int:story_id>/tasks/<int:pk>/finish', TaskFinish.as_view(), name='task_finish'),
    path('projects/<int:project_id>/stories/<int:pk>/list_time', LoggedTimeList.as_view(), name='tracked_time'),
    

    path('projects/<int:project_id>/posts/create', PostCreate.as_view(), name='post_create'),
    path('projects/<int:project_id>/posts', PostList.as_view(), name='post_list'),

    path('projects/<int:project_id>/posts/<int:post_id>/comments/', CommentListView.as_view(), name='comment_list'),
    path('projects/<int:project_id>/posts/<int:post_id>/comments/create/', CreateCommentView.as_view(), name='create_comment'),
    path('projects/<int:project_id>/post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('projects/<int:project_id>/comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),

    path('update-profile/', ProfileUpdateView.as_view(), name='update_profile'),
    path('password-change/', ChangePasswordView.as_view(), name='passwordchange'),

    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('', lambda r: redirect('project_list'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Duplicate URL names are allowed by Django, but we don't want them in this project, so make sure they don't happen
names = [pattern.name for pattern in urlpatterns if getattr(pattern, "name", None)]
assert len(names) == len(set(names)), f"Duplicate URL names: {names}"

scrumapp/models.py
from functools import cached_property

from django.contrib.auth.models import User
from django.db import models
from django.forms import ValidationError
from django.urls import reverse_lazy
from django.utils import timezone

from scrumapp.validators import date_not_in_past


class RoleEnum(models.TextChoices):
    DEVELOPER = "DEV", "Developer"
    SCRUM_MASTER = "SM", "Scrum Master"
    PRODUCT_OWNER = "PO", "Product Owner"

class ProjectMember(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    project = models.ForeignKey("Project", on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=RoleEnum.choices)

class Project(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)

    sprints: 'SprintQuerySet'
    stories: 'StoryQuerySet'

    def __str__(self):
        return self.name
    
    # These use .all() to take advantage of query caching, but we still need to confirm queries are actually cached
    
    @cached_property
    def product_owner(self) -> User:
        for pm in self.projectmember_set.all():
            if pm.role == RoleEnum.PRODUCT_OWNER:
                return pm.user
            
    @cached_property
    def scrum_master(self) -> User:
        for pm in self.projectmember_set.all():
            if pm.role == RoleEnum.SCRUM_MASTER:
                return pm.user
    
    @cached_property
    def developers(self) -> list[User]:
        return [pm.user for pm in self.projectmember_set.all() if pm.role == RoleEnum.DEVELOPER]

    def get_absolute_url(self):
        return reverse_lazy("project_detail", kwargs={"project_id": self.id})
    

# A custom manager for Sprint so we can DRY our queries
class SprintQuerySet(models.QuerySet):
    def active(self):
        now = timezone.now()
        return self.filter(start_date__lte=now, end_date__gte=now)

    def future(self):
        return self.filter(start_date__gt=timezone.now())
    
    def past(self):
        return self.filter(end_date__lt=timezone.now())


class Sprint(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="sprints")
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    velocity = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="Velocity (pts)")

    objects = SprintQuerySet.as_manager()

    def __str__(self):
        return self.name

    def clean(self):
        if self.start_date > self.end_date:
            raise ValidationError({
                "start_date": "Start date cannot be after end date"
            })
        # Only run this validation on new objects (when creating)
        if self.id is None:
            if self.start_date < timezone.now().date():
                raise ValidationError({
                    "start_date": "Start date cannot be in the past"
                })

        # TODO: turn this into a field validation
        if self.velocity == 0:
            raise ValidationError({
                "velocity": "Velocity cannot be 0"
            })

    def get_absolute_url(self):
        return reverse_lazy("sprint_detail", kwargs={"project_id": self.project.id, "pk": self.id})

    def is_future(self):
        return self.start_date > timezone.now().date()

    def is_active(self):
        return self.start_date <= timezone.now().date() and \
            self.end_date >= timezone.now().date()


class StoryQuerySet(models.QuerySet):
    def product_backlog(self):
        return (self.filter(sprint=None)
            .exclude(status=Story.Status.ACCEPTED) |
            self.filter(status=Story.Status.REJECTED)) \
            .exclude(priority=Story.Priority.WONT_HAVE)


class Story(models.Model):
    class Priority(models.IntegerChoices):
        MUST_HAVE = 1, 'Must have'
        SHOULD_HAVE = 2, 'Should have'
        COULD_HAVE = 3, 'Could have'
        WONT_HAVE = 4, "Won't have at this time"

    class Status(models.IntegerChoices):
        UNKNOWN = 0, 'Unknown'
        ACCEPTED = 1, 'Accepted'
        REJECTED = 2, 'Rejected'

    objects = StoryQuerySet.as_manager()

    sprint = models.ForeignKey(Sprint, null=True, blank=True, on_delete=models.SET_NULL)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="stories")
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    acceptance_tests = models.TextField(blank=True)
    priority = models.IntegerField(choices=Priority)
    status = models.IntegerField(choices=Status, default=Status.UNKNOWN)
    business_value = models.FloatField(verbose_name="Business value")
    time_estimate = models.FloatField(verbose_name="Time estimate (pts)", null=True, blank=True)
    finished = models.BooleanField(default=False)
    soft_deleted = models.BooleanField(default=False)

    tasks: 'models.QuerySet[Task]'
    notes: 'models.QuerySet[StoryNotes]'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("story_detail", kwargs={"project_id": self.project.id, "pk": self.id})

    def is_accepted(self):
        return self.status == Story.Status.ACCEPTED

    def is_recjected(self):
        return self.status == Story.Status.REJECTED

    def clean(self):
        if self.business_value is not None:
            if self.business_value <= 0 or self.business_value > 10:
                raise ValidationError({
                    "business_value": "Business value should be between 1 and 10"
                })

    @cached_property
    def is_finished(self):
        finished_tasks_count = self.tasks.filter(status=Task.Status.FINISHED).count()
        return finished_tasks_count == self.tasks.count() and finished_tasks_count > 0
    
    class Meta:
        verbose_name_plural = "stories"

class StoryNotes(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE, related_name="notes")
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    content = models.TextField()
    time_posted = models.DateTimeField(auto_now_add=True)

class Task(models.Model):
    class Status(models.IntegerChoices):
        UNCLAIMED = 0, 'Unclaimed'
        CLAIMED = 1, 'Claimed'
        ACTIVE = 2, 'Active'
        FINISHED = 3, 'Finished'

    story = models.ForeignKey(Story, on_delete=models.CASCADE, related_name="tasks")
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    status = models.IntegerField(choices=Status, default=Status.UNCLAIMED)
    assigned_to = models.ForeignKey("auth.User", on_delete=models.SET_NULL, null=True, blank=True)
    hours = models.IntegerField()
    date = models.DateField(default=timezone.now)
    soft_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class TrackedTime(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="work_logs")
    date = models.DateField(default=timezone.now)
    # Time when the task was started (if not running, this is None)
    started = models.DateTimeField(null=True, blank=True)
    hours = models.FloatField(null=True, blank=True)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)

    class Meta:
        unique_together = ('task', 'date', 'user')


class Post(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    time_posted = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("post_list", kwargs={"project_id": self.project.id})
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    content = models.TextField()
    time_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user.username} on {self.post.title}"

scrumapp/templates/scrumapp/partial/sprint_list.html
<div class="row gx-2">
    {% for sprint in sprints %}
    <div class="col-sm-6 col-xs-12">
        <div class="card mb-2 my-2" style="min-height: 8em;">
            <a href="{{ sprint.get_absolute_url }}" class="card-block text-decoration-none text-reset">
                <div class="card-body">
                    <h5 class="card-title">{{ sprint.name }}</h5>
                    <small class="text-muted">
                        <i class="fas fa-calendar-day"></i>
                        {{sprint.start_date}} &mdash; {{sprint.end_date}}
                    </small>
                    <p class="card-text">{{ sprint.description|truncatewords:20 }}</p>
                </div>
            </a>
        </div>
    </div>
    {% empty %}
    <div class="row">
        <span class="col text-muted my-2 text-center">No sprints here</span>
    </div>
    {% endfor %}
</div>

scrumapp/templates/scrumapp/partial/story_list.html
<div class="row gx-2">
    {% for story in stories %}
    {% if not story.soft_deleted %}
    <div class="col-sm-5 col-xs-12" data-story-id="{{story.id}}">
        <div class="card my-2" style="min-height: 8em;" >
            <a href="{{ story.get_absolute_url }}" class="card-block text-decoration-none text-reset">
                <div class="card-body">
                    <div class="row justify-content-between">
                        <div class="col">
                            <h5 class="card-title">{{ story.title }} <span class="text-muted">[{{story.get_priority_display}}]</span></h5>
                        </div>
                        {% if checkbox %}
                        <div class="col-auto">
                            <input type="checkbox" class="form-check-input" name="stories" value="{{story.id}}">
                        </div>
                        {% endif %}
                    </div>

                    {% if show_tasks %}
                    <small class="mb-2 d-block">
                        {% for task in story.tasks.all %}
                            {% if not task.soft_deleted %}
                            <div>
                                {% if task.status == task.Status.FINISHED %}
                                <i class="fa-regular fa-check-square me-1"></i>
                                {% else %}
                                <i class="fa-regular fa-square me-1"></i>
                                {% endif %}
                                [{{ task.get_status_display }}] {{ task.title | truncatechars:30 }}
                            </div>
                            {% endif %}
                        {% empty %}
                            <div class="col text-muted">No tasks</div>
                        {% endfor %}
                    </small>
                    {% endif %}

                    <small class="card-text text-muted d-block">
                        <i class="fas fa-dollar"></i>
                        <strong>Business value:</strong> {{ story.business_value }} pts
                        {% if show_time_estimate and story.time_estimate %}
						<i class="fas fa-clock ms-1"></i>
                    	<strong>Time est.:</strong> {{ story.time_estimate }} pts
                        {% endif %}
                        {% if story.is_accepted %}
                        <i class="fas fa-check-circle ms-1 text-success"></i> Accepted
						{% endif %}
                        {% if story.is_recjected %}
                        <i class="fas fa-circle-xmark ms-1 text-danger"></i> Rejected
						{% endif %}
                    </small>

                    {% if show_accept and  project.product_owner == request.user and story.is_finished and not story.is_accepted and story.sprint %}
                    <a href="{% url 'story_status' project_id=story.project.id pk=story.id %}" class="btn btn-success btn-sm col-3 my-1">
                       Accept / Reject
                    </a>
                    {% endif %}
                </div>
            </a>
        </div>
    </div>
    {% endif %}
    {% empty %}
    <div class="row">
        <span class="col text-muted my-2 text-center">No stories here</span>
    </div>
    {% endfor %}
</div>

scrumapp/templates/scrumapp/partial/task_list.html
{% load scrumapp %}
<div class="row gx-2">
    {% for task in tasks %}

    <div class="card mb-2 my-2" style="min-height: 8em;">
        <div class="card-block text-decoration-none text-reset">
            <div class="card-body">
                <div class="d-flex justify-content-between">

                    <h5 class="card-title">{{ task.title }}</h5>

                    <div class="d-flex">
                        {% if task.status == task.Status.UNCLAIMED %}
                        <form method="POST" action="{% url 'task_claim' project_id=project.id story_id=task.story.id pk=task.id %}" class="me-2">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-success">Claim</button>
                        </form>
                        {% else %}
                            {% if task.status != task.Status.FINISHED and not active_trackedtime %}
                            <form method="POST" action="{% url 'task_start' project_id=project.id story_id=task.story.id pk=task.id %}" class="me-2">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-sm btn-info">Start Tracking</button>
                            </form>
                                {% if task.status == task.Status.CLAIMED and task.story.sprint is not none %}
                                <form method="POST" action="{% url 'task_unclaim' project_id=project.id story_id=task.story.id pk=task.id %}" class="me-2">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-sm btn-danger">Unclaim</button>
                                </form>
                                <form method="POST" action="{% url 'task_finish' project_id=project.id story_id=task.story.id pk=task.id %}" class="me-2">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-sm btn-success">Finish</button>
                                </form>
                                {% endif %}
                            {% elif active_trackedtime.task == task %}
                            <form method="POST" action="{% url 'task_stop' project_id=project.id story_id=task.story.id pk=task.id %}" class="me-2">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-sm btn-danger">Stop Tracking</button>
                            </form>
                            {% endif %}
                        {% endif %} 
                        <a class="me-2 btn btn-sm btn-warning" href="{% url 'task_edit' project_id=project.id story_id=task.story.id pk=task.id %}" title="Edit"><i class="fas fa-edit"></i> Edit</a>

                        {% if task.status == task.Status.UNCLAIMED %}
                        <form method="POST" action="{% url 'task_delete' project_id=project.id story_id=task.story.id pk=task.id %}" class="me-2">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-danger">
                                <i class="fas fa-trash"></i>
                                Delete
                            </button>
                        </form>
                        {% endif %}
                    </div>

                </div>
                <small>
                    {{task.description|newline_br}}
                </small>
                <small class="card-text">
                    <i class="fas fa-clock"></i>
                    <strong>Time est:</strong> {{ task.hours }} h
                    {% if task.assigned_to %}
                    <i class="fas fa-user ms-2"></i>
                    <strong>Assigned to:</strong> {{ task.assigned_to }}
                    {% endif %}
                </small>  
            </div>
        </div>
    </div>
    
    {% empty %}
    <div class="row">
        <span class="col text-muted my-2 text-center">No tasks here</span>
    </div>
    {% endfor %}
</div>